calc_log_ml <-
function(snp.object, partition){
   #some checks
   if (ncol(snp.object$prior)!=ncol(snp.object$data)) stop("ncol mismatch bwtn prior and data!")
   if (length(partition)!=nrow(snp.object$data)) stop("mismatch bwtn partition and data!")
 
      mA <- t(rowsum(1*(snp.object$data=="A"),partition))
      mR <- t(rowsum(1*(snp.object$data=="R"),partition))
      mN <- t(rowsum(1*(snp.object$data=="N"),partition))
      mD <- t(rowsum(1*(snp.object$data=="D"),partition))
      mB <- t(rowsum(1*(snp.object$data=="B"),partition))
      mC <- t(rowsum(1*(snp.object$data=="C"),partition))
      mE <- t(rowsum(1*(snp.object$data=="E"),partition))
      mQ <- t(rowsum(1*(snp.object$data=="Q"),partition))
      mZ <- t(rowsum(1*(snp.object$data=="Z"),partition))
      mG <- t(rowsum(1*(snp.object$data=="G"),partition))
      mH <- t(rowsum(1*(snp.object$data=="H"),partition))
      mI <- t(rowsum(1*(snp.object$data=="I"),partition))
      mL <- t(rowsum(1*(snp.object$data=="L"),partition))
      mK <- t(rowsum(1*(snp.object$data=="K"),partition))
      mM <- t(rowsum(1*(snp.object$data=="M"),partition))
      mF <- t(rowsum(1*(snp.object$data=="F"),partition))
      mP <- t(rowsum(1*(snp.object$data=="P"),partition))
      mS <- t(rowsum(1*(snp.object$data=="S"),partition))
      mT <- t(rowsum(1*(snp.object$data=="T"),partition))
      mW <- t(rowsum(1*(snp.object$data=="W"),partition))
      mY <- t(rowsum(1*(snp.object$data=="Y"),partition))
      mV <- t(rowsum(1*(snp.object$data=="V"),partition))
 prior <- snp.object$prior
   prior[prior==0] <- 1 #deal with zeros and resulting NAs
 
   #calculate log marginal likelihood
   term1 <- -lgamma(1 + mA+mR+mN+mD+mB+mC+mE+mQ+mZ+mG+mH+mI+mL+mK+mM+mF+mP+mS+mT+mW+mY+mV)
 term2 <- lgamma(prior["A", ] + mA) - lgamma(prior["A", ])
 term2 <- term2 + lgamma(prior["R", ] + mR) - lgamma(prior["R", ])
 term2 <- term2 + lgamma(prior["N", ] + mN) - lgamma(prior["N", ])
 term2 <- term2 + lgamma(prior["D", ] + mD) - lgamma(prior["D", ])
 term2 <- term2 + lgamma(prior["B", ] + mB) - lgamma(prior["B", ])
 term2 <- term2 + lgamma(prior["C", ] + mC) - lgamma(prior["C", ])
 term2 <- term2 + lgamma(prior["E", ] + mE) - lgamma(prior["E", ])
 term2 <- term2 + lgamma(prior["Q", ] + mQ) - lgamma(prior["Q", ])
 term2 <- term2 + lgamma(prior["Z", ] + mZ) - lgamma(prior["Z", ])
 term2 <- term2 + lgamma(prior["G", ] + mG) - lgamma(prior["G", ])
 term2 <- term2 + lgamma(prior["H", ] + mH) - lgamma(prior["H", ])
 term2 <- term2 + lgamma(prior["I", ] + mI) - lgamma(prior["I", ])
 term2 <- term2 + lgamma(prior["L", ] + mL) - lgamma(prior["L", ])
 term2 <- term2 + lgamma(prior["K", ] + mK) - lgamma(prior["K", ])
 term2 <- term2 + lgamma(prior["M", ] + mM) - lgamma(prior["M", ])
 term2 <- term2 + lgamma(prior["F", ] + mF) - lgamma(prior["F", ])
 term2 <- term2 + lgamma(prior["P", ] + mP) - lgamma(prior["P", ])
 term2 <- term2 + lgamma(prior["S", ] + mS) - lgamma(prior["S", ])
 term2 <- term2 + lgamma(prior["T", ] + mT) - lgamma(prior["T", ])
 term2 <- term2 + lgamma(prior["W", ] + mW) - lgamma(prior["W", ])
 term2 <- term2 + lgamma(prior["Y", ] + mY) - lgamma(prior["Y", ])
 term2 <- term2 + lgamma(prior["V", ] + mV) - lgamma(prior["V", ])
 ml <- sum(term1 + term2)
 ml <- ml - log_stirling2(nrow(snp.object$data), length(unique(partition)))
 
   return(ml)
 }
